-- Canonical team table + alias map (2015/16 - 2025/26)
-- 503 teams, 577 aliases. Source A: footystats CL csvs. Source B: football-data xlsx.

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

CREATE TABLE teams (
  team_id            INTEGER PRIMARY KEY,
  canonical_name     TEXT NOT NULL UNIQUE,
  country            TEXT NOT NULL,
  in_cl_source       INTEGER NOT NULL,
  in_domestic_source INTEGER NOT NULL,
  notes              TEXT
);
INSERT INTO "teams" VALUES(1,'Egnatia Rrogozhine','Albania',1,0,NULL);
INSERT INTO "teams" VALUES(2,'KF Tirana','Albania',1,0,'Distinct from Partizani Tirana');
INSERT INTO "teams" VALUES(3,'Kukesi','Albania',1,0,NULL);
INSERT INTO "teams" VALUES(4,'Partizani Tirana','Albania',1,0,'Distinct from KF Tirana');
INSERT INTO "teams" VALUES(5,'Skenderbeu Korce','Albania',1,0,NULL);
INSERT INTO "teams" VALUES(6,'Teuta Durres','Albania',1,0,NULL);
INSERT INTO "teams" VALUES(7,'Atletic Club d''Escaldes','Andorra',1,0,'Distinct from Inter Club d''Escaldes');
INSERT INTO "teams" VALUES(8,'FC Santa Coloma','Andorra',1,0,'Distinct from UE Santa Coloma');
INSERT INTO "teams" VALUES(9,'Inter Club d''Escaldes','Andorra',1,0,'Distinct from Atletic Club d''Escaldes');
INSERT INTO "teams" VALUES(10,'UE Santa Coloma','Andorra',1,0,'Distinct from FC Santa Coloma');
INSERT INTO "teams" VALUES(11,'Alashkert','Armenia',1,0,NULL);
INSERT INTO "teams" VALUES(12,'Artsakh','Armenia',1,0,NULL);
INSERT INTO "teams" VALUES(13,'Avan Academy','Armenia',1,0,NULL);
INSERT INTO "teams" VALUES(14,'Pyunik','Armenia',1,0,NULL);
INSERT INTO "teams" VALUES(15,'Urartu','Armenia',1,0,'Renamed from Banants to Urartu in 2019');
INSERT INTO "teams" VALUES(16,'LASK','Austria',1,0,NULL);
INSERT INTO "teams" VALUES(17,'Rapid Wien','Austria',1,0,NULL);
INSERT INTO "teams" VALUES(18,'Red Bull Salzburg','Austria',1,0,NULL);
INSERT INTO "teams" VALUES(19,'Sturm Graz','Austria',1,0,NULL);
INSERT INTO "teams" VALUES(20,'Neftci Baku','Azerbaijan',1,0,NULL);
INSERT INTO "teams" VALUES(21,'Qarabag','Azerbaijan',1,0,NULL);
INSERT INTO "teams" VALUES(22,'BATE Borisov','Belarus',1,0,NULL);
INSERT INTO "teams" VALUES(23,'Dinamo Brest','Belarus',1,0,'Distinct from Brest (France)');
INSERT INTO "teams" VALUES(24,'Dinamo Minsk','Belarus',1,0,NULL);
INSERT INTO "teams" VALUES(25,'Shakhtyor Soligorsk','Belarus',1,0,'Distinct from Shakhtar Donetsk (Ukraine)');
INSERT INTO "teams" VALUES(26,'Anderlecht','Belgium',1,1,NULL);
INSERT INTO "teams" VALUES(27,'Antwerp','Belgium',1,1,NULL);
INSERT INTO "teams" VALUES(28,'Beerschot','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(29,'Cercle Brugge','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(30,'Charleroi','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(31,'Club Brugge','Belgium',1,1,'Distinct from Cercle Brugge');
INSERT INTO "teams" VALUES(32,'Dender EH','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(33,'Eupen','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(34,'Genk','Belgium',1,1,NULL);
INSERT INTO "teams" VALUES(35,'Gent','Belgium',1,1,NULL);
INSERT INTO "teams" VALUES(36,'Kortrijk','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(37,'Lokeren','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(38,'Mechelen','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(39,'Mouscron','Belgium',0,1,'Same club as ''Mouscron-Peruwelz''');
INSERT INTO "teams" VALUES(40,'Oostende','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(41,'Oud-Heverlee Leuven','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(42,'RAAL La Louviere','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(43,'RWD Molenbeek','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(44,'Seraing','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(45,'Sint-Truiden','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(46,'Standard Liege','Belgium',1,1,NULL);
INSERT INTO "teams" VALUES(47,'Union Saint-Gilloise','Belgium',1,1,'Distinct from Union Berlin');
INSERT INTO "teams" VALUES(48,'Waasland-Beveren','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(49,'Westerlo','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(50,'Zulte Waregem','Belgium',0,1,NULL);
INSERT INTO "teams" VALUES(51,'Borac Banja Luka','Bosnia and Herzegovina',1,0,NULL);
INSERT INTO "teams" VALUES(52,'FK Sarajevo','Bosnia and Herzegovina',1,0,NULL);
INSERT INTO "teams" VALUES(53,'Zrinjski Mostar','Bosnia and Herzegovina',1,0,NULL);
INSERT INTO "teams" VALUES(54,'Ludogorets Razgrad','Bulgaria',1,0,NULL);
INSERT INTO "teams" VALUES(55,'Dinamo Zagreb','Croatia',1,0,'Distinct from Lokomotiva Zagreb');
INSERT INTO "teams" VALUES(56,'Lokomotiva Zagreb','Croatia',1,0,'Distinct from Dinamo Zagreb');
INSERT INTO "teams" VALUES(57,'Rijeka','Croatia',1,0,NULL);
INSERT INTO "teams" VALUES(58,'AEK Larnaca','Cyprus',1,0,'Distinct from AEK Athens (Greece)');
INSERT INTO "teams" VALUES(59,'APOEL Nicosia','Cyprus',1,0,NULL);
INSERT INTO "teams" VALUES(60,'Apollon Limassol','Cyprus',1,0,'NOT the same club as domestic ''Apollon'' (Apollon Smyrnis, Greece)');
INSERT INTO "teams" VALUES(61,'Aris Limassol','Cyprus',1,0,'NOT the same club as domestic ''Aris'' (Aris Thessaloniki, Greece)');
INSERT INTO "teams" VALUES(62,'Omonia Nicosia','Cyprus',1,0,NULL);
INSERT INTO "teams" VALUES(63,'Pafos','Cyprus',1,0,NULL);
INSERT INTO "teams" VALUES(64,'Slavia Prague','Czechia',1,0,NULL);
INSERT INTO "teams" VALUES(65,'Sparta Prague','Czechia',1,0,'Distinct from Sparta Rotterdam');
INSERT INTO "teams" VALUES(66,'Viktoria Plzen','Czechia',1,0,NULL);
INSERT INTO "teams" VALUES(67,'Brondby','Denmark',1,0,NULL);
INSERT INTO "teams" VALUES(68,'FC Copenhagen','Denmark',1,0,NULL);
INSERT INTO "teams" VALUES(69,'Midtjylland','Denmark',1,0,NULL);
INSERT INTO "teams" VALUES(70,'Arsenal','England',1,1,NULL);
INSERT INTO "teams" VALUES(71,'Aston Villa','England',1,1,NULL);
INSERT INTO "teams" VALUES(72,'Bournemouth','England',0,1,NULL);
INSERT INTO "teams" VALUES(73,'Brentford','England',0,1,NULL);
INSERT INTO "teams" VALUES(74,'Brighton & Hove Albion','England',0,1,NULL);
INSERT INTO "teams" VALUES(75,'Burnley','England',0,1,NULL);
INSERT INTO "teams" VALUES(76,'Chelsea','England',1,1,NULL);
INSERT INTO "teams" VALUES(77,'Crystal Palace','England',0,1,NULL);
INSERT INTO "teams" VALUES(78,'Everton','England',0,1,NULL);
INSERT INTO "teams" VALUES(79,'Fulham','England',0,1,NULL);
INSERT INTO "teams" VALUES(80,'Huddersfield Town','England',0,1,NULL);
INSERT INTO "teams" VALUES(81,'Hull City','England',0,1,NULL);
INSERT INTO "teams" VALUES(82,'Ipswich Town','England',0,1,NULL);
INSERT INTO "teams" VALUES(83,'Leeds United','England',0,1,NULL);
INSERT INTO "teams" VALUES(84,'Leicester City','England',1,1,NULL);
INSERT INTO "teams" VALUES(85,'Liverpool','England',1,1,NULL);
INSERT INTO "teams" VALUES(86,'Luton Town','England',0,1,NULL);
INSERT INTO "teams" VALUES(87,'Manchester City','England',1,1,NULL);
INSERT INTO "teams" VALUES(88,'Manchester United','England',1,1,NULL);
INSERT INTO "teams" VALUES(89,'Middlesbrough','England',0,1,NULL);
INSERT INTO "teams" VALUES(90,'Newcastle United','England',1,1,NULL);
INSERT INTO "teams" VALUES(91,'Norwich City','England',0,1,NULL);
INSERT INTO "teams" VALUES(92,'Nottingham Forest','England',0,1,NULL);
INSERT INTO "teams" VALUES(93,'Sheffield United','England',0,1,NULL);
INSERT INTO "teams" VALUES(94,'Southampton','England',0,1,NULL);
INSERT INTO "teams" VALUES(95,'Stoke City','England',0,1,NULL);
INSERT INTO "teams" VALUES(96,'Sunderland','England',0,1,NULL);
INSERT INTO "teams" VALUES(97,'Tottenham Hotspur','England',1,1,NULL);
INSERT INTO "teams" VALUES(98,'Watford','England',0,1,NULL);
INSERT INTO "teams" VALUES(99,'West Bromwich Albion','England',0,1,NULL);
INSERT INTO "teams" VALUES(100,'West Ham United','England',0,1,NULL);
INSERT INTO "teams" VALUES(101,'Wolverhampton Wanderers','England',0,1,NULL);
INSERT INTO "teams" VALUES(102,'FCI Tallinn','Estonia',1,0,'Merged with Levadia in 2017; kept separate as a distinct pre-merger entity');
INSERT INTO "teams" VALUES(103,'Flora Tallinn','Estonia',1,0,NULL);
INSERT INTO "teams" VALUES(104,'Levadia Tallinn','Estonia',1,0,'FCI Tallinn merged into Levadia in 2017');
INSERT INTO "teams" VALUES(105,'Nomme Kalju','Estonia',1,0,NULL);
INSERT INTO "teams" VALUES(106,'B36 Torshavn','Faroe Islands',1,0,NULL);
INSERT INTO "teams" VALUES(107,'HB Torshavn','Faroe Islands',1,0,NULL);
INSERT INTO "teams" VALUES(108,'KI Klaksvik','Faroe Islands',1,0,NULL);
INSERT INTO "teams" VALUES(109,'Vikingur Gota','Faroe Islands',1,0,'Distinct from Vikingur Reykjavik (Iceland)');
INSERT INTO "teams" VALUES(110,'HJK Helsinki','Finland',1,0,NULL);
INSERT INTO "teams" VALUES(111,'IFK Mariehamn','Finland',1,0,NULL);
INSERT INTO "teams" VALUES(112,'KuPS','Finland',1,0,NULL);
INSERT INTO "teams" VALUES(113,'SJK Seinajoki','Finland',1,0,NULL);
INSERT INTO "teams" VALUES(114,'AC Ajaccio','France',0,1,'Distinct from Gazelec Ajaccio');
INSERT INTO "teams" VALUES(115,'Amiens','France',0,1,NULL);
INSERT INTO "teams" VALUES(116,'Angers','France',0,1,NULL);
INSERT INTO "teams" VALUES(117,'Auxerre','France',0,1,NULL);
INSERT INTO "teams" VALUES(118,'Bastia','France',0,1,NULL);
INSERT INTO "teams" VALUES(119,'Bordeaux','France',0,1,NULL);
INSERT INTO "teams" VALUES(120,'Brest','France',1,1,'Stade Brestois. Distinct from Dinamo Brest (Belarus)');
INSERT INTO "teams" VALUES(121,'Caen','France',0,1,NULL);
INSERT INTO "teams" VALUES(122,'Clermont Foot','France',0,1,NULL);
INSERT INTO "teams" VALUES(123,'Dijon','France',0,1,NULL);
INSERT INTO "teams" VALUES(124,'Gazelec Ajaccio','France',0,1,'Distinct from AC Ajaccio');
INSERT INTO "teams" VALUES(125,'Guingamp','France',0,1,NULL);
INSERT INTO "teams" VALUES(126,'Le Havre','France',0,1,NULL);
INSERT INTO "teams" VALUES(127,'Lens','France',1,1,NULL);
INSERT INTO "teams" VALUES(128,'Lille','France',1,1,NULL);
INSERT INTO "teams" VALUES(129,'Lorient','France',0,1,NULL);
INSERT INTO "teams" VALUES(130,'Lyon','France',1,1,NULL);
INSERT INTO "teams" VALUES(131,'Marseille','France',1,1,NULL);
INSERT INTO "teams" VALUES(132,'Metz','France',0,1,NULL);
INSERT INTO "teams" VALUES(133,'Monaco','France',1,1,NULL);
INSERT INTO "teams" VALUES(134,'Montpellier','France',0,1,NULL);
INSERT INTO "teams" VALUES(135,'Nancy','France',0,1,NULL);
INSERT INTO "teams" VALUES(136,'Nantes','France',0,1,NULL);
INSERT INTO "teams" VALUES(137,'Nice','France',1,1,NULL);
INSERT INTO "teams" VALUES(138,'Nimes','France',0,1,NULL);
INSERT INTO "teams" VALUES(139,'Paris FC','France',0,1,'Distinct from Paris Saint-Germain');
INSERT INTO "teams" VALUES(140,'Paris Saint-Germain','France',1,1,'Distinct from Paris FC');
INSERT INTO "teams" VALUES(141,'Reims','France',0,1,NULL);
INSERT INTO "teams" VALUES(142,'Rennes','France',1,1,NULL);
INSERT INTO "teams" VALUES(143,'Saint-Etienne','France',0,1,NULL);
INSERT INTO "teams" VALUES(144,'Strasbourg','France',0,1,NULL);
INSERT INTO "teams" VALUES(145,'Toulouse','France',0,1,NULL);
INSERT INTO "teams" VALUES(146,'Troyes','France',0,1,NULL);
INSERT INTO "teams" VALUES(147,'Dila Gori','Georgia',1,0,NULL);
INSERT INTO "teams" VALUES(148,'Dinamo Batumi','Georgia',1,0,'Distinct from Dinamo Tbilisi');
INSERT INTO "teams" VALUES(149,'Dinamo Tbilisi','Georgia',1,0,'Distinct from Dinamo Batumi');
INSERT INTO "teams" VALUES(150,'Saburtalo Tbilisi','Georgia',1,0,NULL);
INSERT INTO "teams" VALUES(151,'Samtredia','Georgia',1,0,NULL);
INSERT INTO "teams" VALUES(152,'Torpedo Kutaisi','Georgia',1,0,NULL);
INSERT INTO "teams" VALUES(153,'Arminia Bielefeld','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(154,'Augsburg','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(155,'Bayer Leverkusen','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(156,'Bayern Munich','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(157,'Bochum','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(158,'Borussia Dortmund','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(159,'Borussia Monchengladbach','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(160,'Darmstadt 98','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(161,'Eintracht Frankfurt','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(162,'FC Koln','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(163,'Fortuna Dusseldorf','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(164,'Freiburg','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(165,'Greuther Furth','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(166,'Hamburger SV','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(167,'Hannover 96','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(168,'Heidenheim','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(169,'Hertha Berlin','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(170,'Hoffenheim','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(171,'Holstein Kiel','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(172,'Ingolstadt','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(173,'Mainz 05','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(174,'Nurnberg','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(175,'Paderborn','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(176,'RB Leipzig','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(177,'Schalke 04','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(178,'St Pauli','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(179,'Union Berlin','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(180,'VfB Stuttgart','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(181,'Werder Bremen','Germany',0,1,NULL);
INSERT INTO "teams" VALUES(182,'Wolfsburg','Germany',1,1,NULL);
INSERT INTO "teams" VALUES(183,'Europa FC','Gibraltar',1,0,NULL);
INSERT INTO "teams" VALUES(184,'Lincoln Red Imps','Gibraltar',1,0,NULL);
INSERT INTO "teams" VALUES(185,'AEK Athens','Greece',1,1,'Distinct from AEK Larnaca (Cyprus)');
INSERT INTO "teams" VALUES(186,'Apollon Smyrnis','Greece',0,1,'NOT the same club as CL ''Apollon'' (Apollon Limassol, Cyprus)');
INSERT INTO "teams" VALUES(187,'Aris Thessaloniki','Greece',0,1,'NOT the same club as CL ''Aris'' (Aris Limassol, Cyprus)');
INSERT INTO "teams" VALUES(188,'Asteras Tripolis','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(189,'Atromitos','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(190,'Ionikos','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(191,'Iraklis','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(192,'Kallithea','Greece',0,1,'Distinct from Kalloni');
INSERT INTO "teams" VALUES(193,'Kalloni','Greece',0,1,'Distinct from Kallithea');
INSERT INTO "teams" VALUES(194,'Kerkyra','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(195,'Kifisia','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(196,'Lamia','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(197,'Larissa','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(198,'Levadeiakos','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(199,'OFI Crete','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(200,'Olympiakos','Greece',1,1,NULL);
INSERT INTO "teams" VALUES(201,'PAOK','Greece',1,1,NULL);
INSERT INTO "teams" VALUES(202,'PAS Giannina','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(203,'Panathinaikos','Greece',1,1,NULL);
INSERT INTO "teams" VALUES(204,'Panetolikos','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(205,'Panionios','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(206,'Panserraikos','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(207,'Panthrakikos','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(208,'Platanias','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(209,'Veria','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(210,'Volos','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(211,'Xanthi','Greece',0,1,NULL);
INSERT INTO "teams" VALUES(212,'Budapest Honved','Hungary',1,0,NULL);
INSERT INTO "teams" VALUES(213,'Fehervar','Hungary',1,0,'Renamed from Videoton to MOL Fehervar in 2018');
INSERT INTO "teams" VALUES(214,'Ferencvaros','Hungary',1,0,NULL);
INSERT INTO "teams" VALUES(215,'Breidablik','Iceland',1,0,NULL);
INSERT INTO "teams" VALUES(216,'FH Hafnarfjordur','Iceland',1,0,NULL);
INSERT INTO "teams" VALUES(217,'KR Reykjavik','Iceland',1,0,NULL);
INSERT INTO "teams" VALUES(218,'Stjarnan','Iceland',1,0,NULL);
INSERT INTO "teams" VALUES(219,'Valur','Iceland',1,0,NULL);
INSERT INTO "teams" VALUES(220,'Vikingur Reykjavik','Iceland',1,0,'Distinct from Vikingur Gota (Faroe Islands)');
INSERT INTO "teams" VALUES(221,'Hapoel Beer Sheva','Israel',1,0,NULL);
INSERT INTO "teams" VALUES(222,'Maccabi Haifa','Israel',1,0,NULL);
INSERT INTO "teams" VALUES(223,'Maccabi Tel Aviv','Israel',1,0,NULL);
INSERT INTO "teams" VALUES(224,'AC Milan','Italy',1,1,'Domestic ''Milan'' = AC Milan; domestic ''Inter'' = Internazionale');
INSERT INTO "teams" VALUES(225,'Atalanta','Italy',1,1,NULL);
INSERT INTO "teams" VALUES(226,'Benevento','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(227,'Bologna','Italy',1,1,NULL);
INSERT INTO "teams" VALUES(228,'Brescia','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(229,'Cagliari','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(230,'Carpi','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(231,'Chievo Verona','Italy',0,1,'Distinct from Hellas Verona');
INSERT INTO "teams" VALUES(232,'Como','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(233,'Cremonese','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(234,'Crotone','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(235,'Empoli','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(236,'Fiorentina','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(237,'Frosinone','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(238,'Genoa','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(239,'Hellas Verona','Italy',0,1,'Distinct from Chievo Verona');
INSERT INTO "teams" VALUES(240,'Inter Milan','Italy',1,1,NULL);
INSERT INTO "teams" VALUES(241,'Juventus','Italy',1,1,NULL);
INSERT INTO "teams" VALUES(242,'Lazio','Italy',1,1,NULL);
INSERT INTO "teams" VALUES(243,'Lecce','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(244,'Monza','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(245,'Napoli','Italy',1,1,NULL);
INSERT INTO "teams" VALUES(246,'Palermo','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(247,'Parma','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(248,'Pescara','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(249,'Pisa','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(250,'Roma','Italy',1,1,NULL);
INSERT INTO "teams" VALUES(251,'SPAL','Italy',0,1,'Distinct from Spezia');
INSERT INTO "teams" VALUES(252,'Salernitana','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(253,'Sampdoria','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(254,'Sassuolo','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(255,'Spezia','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(256,'Torino','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(257,'Udinese','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(258,'Venezia','Italy',0,1,NULL);
INSERT INTO "teams" VALUES(259,'Astana','Kazakhstan',1,0,'Distinct from Astra Giurgiu (Romania)');
INSERT INTO "teams" VALUES(260,'Kairat Almaty','Kazakhstan',1,0,NULL);
INSERT INTO "teams" VALUES(261,'Ordabasy','Kazakhstan',1,0,NULL);
INSERT INTO "teams" VALUES(262,'Tobol Kostanay','Kazakhstan',1,0,NULL);
INSERT INTO "teams" VALUES(263,'Ballkani','Kosovo',1,0,NULL);
INSERT INTO "teams" VALUES(264,'Drita','Kosovo',1,0,NULL);
INSERT INTO "teams" VALUES(265,'Feronikeli','Kosovo',1,0,NULL);
INSERT INTO "teams" VALUES(266,'Prishtina','Kosovo',1,0,NULL);
INSERT INTO "teams" VALUES(267,'Trepca''89','Kosovo',1,0,NULL);
INSERT INTO "teams" VALUES(268,'Liepaja','Latvia',1,0,NULL);
INSERT INTO "teams" VALUES(269,'Riga FC','Latvia',1,0,'Distinct from Rigas FS (RFS)');
INSERT INTO "teams" VALUES(270,'Rigas FS','Latvia',1,0,'RFS. Distinct from Riga FC');
INSERT INTO "teams" VALUES(271,'Spartaks Jurmala','Latvia',1,0,NULL);
INSERT INTO "teams" VALUES(272,'Valmiera','Latvia',1,0,NULL);
INSERT INTO "teams" VALUES(273,'Ventspils','Latvia',1,0,NULL);
INSERT INTO "teams" VALUES(274,'Panevezys','Lithuania',1,0,NULL);
INSERT INTO "teams" VALUES(275,'Suduva','Lithuania',1,0,NULL);
INSERT INTO "teams" VALUES(276,'Zalgiris Vilnius','Lithuania',1,0,NULL);
INSERT INTO "teams" VALUES(277,'Differdange 03','Luxembourg',1,0,NULL);
INSERT INTO "teams" VALUES(278,'F91 Dudelange','Luxembourg',1,0,NULL);
INSERT INTO "teams" VALUES(279,'Fola Esch','Luxembourg',1,0,NULL);
INSERT INTO "teams" VALUES(280,'Swift Hesperange','Luxembourg',1,0,NULL);
INSERT INTO "teams" VALUES(281,'Floriana','Malta',1,0,NULL);
INSERT INTO "teams" VALUES(282,'Hamrun Spartans','Malta',1,0,NULL);
INSERT INTO "teams" VALUES(283,'Hibernians','Malta',1,0,'NOT the same club as domestic ''Hibernian'' (Scotland)');
INSERT INTO "teams" VALUES(284,'Valletta','Malta',1,0,NULL);
INSERT INTO "teams" VALUES(285,'Milsami Orhei','Moldova',1,0,NULL);
INSERT INTO "teams" VALUES(286,'Petrocub Hincesti','Moldova',1,0,NULL);
INSERT INTO "teams" VALUES(287,'Sheriff Tiraspol','Moldova',1,0,NULL);
INSERT INTO "teams" VALUES(288,'Buducnost Podgorica','Montenegro',1,0,NULL);
INSERT INTO "teams" VALUES(289,'Decic','Montenegro',1,0,NULL);
INSERT INTO "teams" VALUES(290,'Mladost Podgorica','Montenegro',1,0,NULL);
INSERT INTO "teams" VALUES(291,'Rudar Pljevlja','Montenegro',1,0,NULL);
INSERT INTO "teams" VALUES(292,'Sutjeska Niksic','Montenegro',1,0,NULL);
INSERT INTO "teams" VALUES(293,'ADO Den Haag','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(294,'AZ Alkmaar','Netherlands',1,1,NULL);
INSERT INTO "teams" VALUES(295,'Ajax','Netherlands',1,1,NULL);
INSERT INTO "teams" VALUES(296,'Almere City','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(297,'Cambuur','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(298,'De Graafschap','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(299,'Emmen','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(300,'Excelsior','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(301,'Feyenoord','Netherlands',1,1,NULL);
INSERT INTO "teams" VALUES(302,'Fortuna Sittard','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(303,'Go Ahead Eagles','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(304,'Groningen','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(305,'Heerenveen','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(306,'Heracles Almelo','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(307,'NAC Breda','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(308,'NEC Nijmegen','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(309,'PEC Zwolle','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(310,'PSV Eindhoven','Netherlands',1,1,NULL);
INSERT INTO "teams" VALUES(311,'RKC Waalwijk','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(312,'Roda JC','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(313,'Sparta Rotterdam','Netherlands',0,1,'Distinct from Sparta Praha');
INSERT INTO "teams" VALUES(314,'Telstar','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(315,'Twente','Netherlands',1,1,NULL);
INSERT INTO "teams" VALUES(316,'Utrecht','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(317,'VVV-Venlo','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(318,'Vitesse','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(319,'Volendam','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(320,'Willem II','Netherlands',0,1,NULL);
INSERT INTO "teams" VALUES(321,'Shkendija','North Macedonia',1,0,NULL);
INSERT INTO "teams" VALUES(322,'Shkupi','North Macedonia',1,0,NULL);
INSERT INTO "teams" VALUES(323,'Sileks','North Macedonia',1,0,NULL);
INSERT INTO "teams" VALUES(324,'Struga','North Macedonia',1,0,NULL);
INSERT INTO "teams" VALUES(325,'Vardar Skopje','North Macedonia',1,0,NULL);
INSERT INTO "teams" VALUES(326,'Crusaders','Northern Ireland',1,0,NULL);
INSERT INTO "teams" VALUES(327,'Larne','Northern Ireland',1,0,NULL);
INSERT INTO "teams" VALUES(328,'Linfield','Northern Ireland',1,0,NULL);
INSERT INTO "teams" VALUES(329,'Bodo/Glimt','Norway',1,0,NULL);
INSERT INTO "teams" VALUES(330,'Brann','Norway',1,0,NULL);
INSERT INTO "teams" VALUES(331,'Molde','Norway',1,0,NULL);
INSERT INTO "teams" VALUES(332,'Rosenborg','Norway',1,0,NULL);
INSERT INTO "teams" VALUES(333,'Jagiellonia Bialystok','Poland',1,0,NULL);
INSERT INTO "teams" VALUES(334,'Lech Poznan','Poland',1,0,NULL);
INSERT INTO "teams" VALUES(335,'Legia Warsaw','Poland',1,0,NULL);
INSERT INTO "teams" VALUES(336,'Piast Gliwice','Poland',1,0,NULL);
INSERT INTO "teams" VALUES(337,'Rakow Czestochowa','Poland',1,0,NULL);
INSERT INTO "teams" VALUES(338,'AVS','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(339,'Academica','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(340,'Alverca','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(341,'Arouca','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(342,'Belenenses','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(343,'Benfica','Portugal',1,1,NULL);
INSERT INTO "teams" VALUES(344,'Boavista','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(345,'Casa Pia','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(346,'Chaves','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(347,'Desportivo Aves','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(348,'Estoril','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(349,'Estrela Amadora','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(350,'Famalicao','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(351,'Farense','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(352,'Feirense','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(353,'Gil Vicente','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(354,'Maritimo','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(355,'Moreirense','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(356,'Nacional','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(357,'Pacos de Ferreira','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(358,'Portimonense','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(359,'Porto','Portugal',1,1,NULL);
INSERT INTO "teams" VALUES(360,'Rio Ave','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(361,'Santa Clara','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(362,'Sporting Braga','Portugal',1,1,NULL);
INSERT INTO "teams" VALUES(363,'Sporting CP','Portugal',1,1,'Domestic ''Sp Lisbon'' = Sporting Clube de Portugal');
INSERT INTO "teams" VALUES(364,'Tondela','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(365,'Uniao da Madeira','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(366,'Vitoria Guimaraes','Portugal',0,1,'Distinct from Vitoria Setubal');
INSERT INTO "teams" VALUES(367,'Vitoria Setubal','Portugal',0,1,'Distinct from Vitoria Guimaraes');
INSERT INTO "teams" VALUES(368,'Vizela','Portugal',0,1,NULL);
INSERT INTO "teams" VALUES(369,'Cork City','Republic of Ireland',1,0,NULL);
INSERT INTO "teams" VALUES(370,'Dundalk','Republic of Ireland',1,0,NULL);
INSERT INTO "teams" VALUES(371,'Shamrock Rovers','Republic of Ireland',1,0,NULL);
INSERT INTO "teams" VALUES(372,'Shelbourne','Republic of Ireland',1,0,NULL);
INSERT INTO "teams" VALUES(373,'Astra Giurgiu','Romania',1,0,'Distinct from Astana (Kazakhstan)');
INSERT INTO "teams" VALUES(374,'CFR Cluj','Romania',1,0,NULL);
INSERT INTO "teams" VALUES(375,'FCSB','Romania',1,0,NULL);
INSERT INTO "teams" VALUES(376,'Farul Constanta','Romania',1,0,'Post-2021 merger with Viitorul; kept separate as a distinct entity');
INSERT INTO "teams" VALUES(377,'Viitorul Constanta','Romania',1,0,'Merged with Farul in 2021');
INSERT INTO "teams" VALUES(378,'CSKA Moscow','Russia',1,0,NULL);
INSERT INTO "teams" VALUES(379,'Krasnodar','Russia',1,0,NULL);
INSERT INTO "teams" VALUES(380,'Lokomotiv Moscow','Russia',1,0,NULL);
INSERT INTO "teams" VALUES(381,'Rostov','Russia',1,0,NULL);
INSERT INTO "teams" VALUES(382,'Spartak Moscow','Russia',1,0,'Distinct from Spartak Trnava (Slovakia)');
INSERT INTO "teams" VALUES(383,'Zenit St Petersburg','Russia',1,0,NULL);
INSERT INTO "teams" VALUES(384,'Folgore','San Marino',1,0,NULL);
INSERT INTO "teams" VALUES(385,'La Fiorita','San Marino',1,0,NULL);
INSERT INTO "teams" VALUES(386,'Tre Fiori','San Marino',1,0,NULL);
INSERT INTO "teams" VALUES(387,'Tre Penne','San Marino',1,0,NULL);
INSERT INTO "teams" VALUES(388,'Virtus','San Marino',1,0,NULL);
INSERT INTO "teams" VALUES(389,'Aberdeen','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(390,'Celtic','Scotland',1,1,NULL);
INSERT INTO "teams" VALUES(391,'Dundee','Scotland',0,1,'Distinct from Dundee United');
INSERT INTO "teams" VALUES(392,'Dundee United','Scotland',0,1,'Distinct from Dundee');
INSERT INTO "teams" VALUES(393,'Falkirk','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(394,'Hamilton Academical','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(395,'Heart of Midlothian','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(396,'Hibernian','Scotland',0,1,'NOT the same club as CL ''Hibernians'' (Malta)');
INSERT INTO "teams" VALUES(397,'Inverness Caledonian Thistle','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(398,'Kilmarnock','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(399,'Livingston','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(400,'Motherwell','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(401,'Partick Thistle','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(402,'Rangers','Scotland',1,1,NULL);
INSERT INTO "teams" VALUES(403,'Ross County','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(404,'St Johnstone','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(405,'St Mirren','Scotland',0,1,NULL);
INSERT INTO "teams" VALUES(406,'Partizan Belgrade','Serbia',1,0,'Distinct from Partizani Tirana (Albania)');
INSERT INTO "teams" VALUES(407,'Red Star Belgrade','Serbia',1,0,NULL);
INSERT INTO "teams" VALUES(408,'TSC Backa Topola','Serbia',1,0,NULL);
INSERT INTO "teams" VALUES(409,'Slovan Bratislava','Slovakia',1,0,NULL);
INSERT INTO "teams" VALUES(410,'Spartak Trnava','Slovakia',1,0,'Distinct from Spartak Moscow (Russia)');
INSERT INTO "teams" VALUES(411,'Trencin','Slovakia',1,0,NULL);
INSERT INTO "teams" VALUES(412,'Zilina','Slovakia',1,0,NULL);
INSERT INTO "teams" VALUES(413,'Celje','Slovenia',1,0,NULL);
INSERT INTO "teams" VALUES(414,'Maribor','Slovenia',1,0,NULL);
INSERT INTO "teams" VALUES(415,'Mura','Slovenia',1,0,NULL);
INSERT INTO "teams" VALUES(416,'Olimpija Ljubljana','Slovenia',1,0,NULL);
INSERT INTO "teams" VALUES(417,'Alaves','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(418,'Almeria','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(419,'Athletic Bilbao','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(420,'Atletico Madrid','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(421,'Barcelona','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(422,'Cadiz','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(423,'Celta Vigo','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(424,'Deportivo La Coruna','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(425,'Eibar','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(426,'Elche','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(427,'Espanyol','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(428,'Getafe','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(429,'Girona','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(430,'Granada','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(431,'Huesca','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(432,'Las Palmas','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(433,'Leganes','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(434,'Levante','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(435,'Malaga','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(436,'Mallorca','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(437,'Osasuna','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(438,'Rayo Vallecano','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(439,'Real Betis','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(440,'Real Madrid','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(441,'Real Oviedo','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(442,'Real Sociedad','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(443,'Real Valladolid','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(444,'Sevilla','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(445,'Sporting Gijon','Spain',0,1,NULL);
INSERT INTO "teams" VALUES(446,'Valencia','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(447,'Villarreal','Spain',1,1,NULL);
INSERT INTO "teams" VALUES(448,'AIK','Sweden',1,0,NULL);
INSERT INTO "teams" VALUES(449,'Djurgarden','Sweden',1,0,NULL);
INSERT INTO "teams" VALUES(450,'Hacken','Sweden',1,0,NULL);
INSERT INTO "teams" VALUES(451,'Malmo FF','Sweden',1,0,NULL);
INSERT INTO "teams" VALUES(452,'Norrkoping','Sweden',1,0,NULL);
INSERT INTO "teams" VALUES(453,'Basel','Switzerland',1,0,NULL);
INSERT INTO "teams" VALUES(454,'Lugano','Switzerland',1,0,NULL);
INSERT INTO "teams" VALUES(455,'Servette','Switzerland',1,0,NULL);
INSERT INTO "teams" VALUES(456,'Young Boys','Switzerland',1,0,NULL);
INSERT INTO "teams" VALUES(457,'Zurich','Switzerland',1,0,NULL);
INSERT INTO "teams" VALUES(458,'Adana Demirspor','Turkey',0,1,'Distinct from Adanaspor');
INSERT INTO "teams" VALUES(459,'Adanaspor','Turkey',0,1,'Distinct from Adana Demirspor');
INSERT INTO "teams" VALUES(460,'Akhisarspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(461,'Alanyaspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(462,'Altay','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(463,'Ankaragucu','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(464,'Antalyaspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(465,'Besiktas','Turkey',1,1,NULL);
INSERT INTO "teams" VALUES(466,'Bodrumspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(467,'Bursaspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(468,'Caykur Rizespor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(469,'Denizlispor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(470,'Erzurumspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(471,'Eskisehirspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(472,'Eyupspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(473,'Fatih Karagumruk','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(474,'Fenerbahce','Turkey',1,1,NULL);
INSERT INTO "teams" VALUES(475,'Galatasaray','Turkey',1,1,NULL);
INSERT INTO "teams" VALUES(476,'Gaziantep FK','Turkey',0,1,'Founded 2018; distinct from the older Gaziantepspor');
INSERT INTO "teams" VALUES(477,'Gaziantepspor','Turkey',0,1,'Distinct from Gaziantep FK');
INSERT INTO "teams" VALUES(478,'Genclerbirligi','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(479,'Giresunspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(480,'Goztepe','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(481,'Hatayspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(482,'Istanbul Basaksehir','Turkey',1,1,'football-data ''Buyuksehyr'' = old name Istanbul Buyuksehir Belediyespor');
INSERT INTO "teams" VALUES(483,'Istanbulspor','Turkey',0,1,'Distinct from Istanbul Basaksehir');
INSERT INTO "teams" VALUES(484,'Karabukspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(485,'Kasimpasa','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(486,'Kayserispor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(487,'Kocaelispor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(488,'Konyaspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(489,'Mersin Idman Yurdu','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(490,'Osmanlispor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(491,'Pendikspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(492,'Samsunspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(493,'Sivasspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(494,'Trabzonspor','Turkey',1,1,NULL);
INSERT INTO "teams" VALUES(495,'Umraniyespor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(496,'Yeni Malatyaspor','Turkey',0,1,NULL);
INSERT INTO "teams" VALUES(497,'Dnipro-1','Ukraine',1,0,NULL);
INSERT INTO "teams" VALUES(498,'Dynamo Kyiv','Ukraine',1,0,NULL);
INSERT INTO "teams" VALUES(499,'Shakhtar Donetsk','Ukraine',1,0,'Distinct from Shakhtyor Soligorsk (Belarus)');
INSERT INTO "teams" VALUES(500,'Cardiff City','Wales',0,1,'Welsh club competing in the English league system');
INSERT INTO "teams" VALUES(501,'Connah''s Quay Nomads','Wales',1,0,NULL);
INSERT INTO "teams" VALUES(502,'Swansea City','Wales',0,1,'Welsh club competing in the English league system');
INSERT INTO "teams" VALUES(503,'The New Saints','Wales',1,0,NULL);

CREATE TABLE team_aliases (
  alias      TEXT NOT NULL,
  source     TEXT NOT NULL,
  league     TEXT,
  alias_norm TEXT NOT NULL,
  team_id    INTEGER NOT NULL REFERENCES teams(team_id),
  PRIMARY KEY (alias, source, league)
);
INSERT INTO "team_aliases" VALUES('Egnatia Rrogozhinë','footystats','CL','egnatia rrogozhine',1);
INSERT INTO "team_aliases" VALUES('Tirana','footystats','CL','tirana',2);
INSERT INTO "team_aliases" VALUES('Kukësi','footystats','CL','kukesi',3);
INSERT INTO "team_aliases" VALUES('Partizani Tirana','footystats','CL','partizani tirana',4);
INSERT INTO "team_aliases" VALUES('Skënderbeu Korçë','footystats','CL','skenderbeu korce',5);
INSERT INTO "team_aliases" VALUES('Teuta Durrës','footystats','CL','teuta durres',6);
INSERT INTO "team_aliases" VALUES('Atlètic Club d''Escaldes','footystats','CL','atletic club d escaldes',7);
INSERT INTO "team_aliases" VALUES('FC Santa Coloma','footystats','CL','fc santa coloma',8);
INSERT INTO "team_aliases" VALUES('Inter Club d''Escaldes','footystats','CL','inter club d escaldes',9);
INSERT INTO "team_aliases" VALUES('UE Santa Coloma','footystats','CL','ue santa coloma',10);
INSERT INTO "team_aliases" VALUES('Alashkert','footystats','CL','alashkert',11);
INSERT INTO "team_aliases" VALUES('Artsakh','footystats','CL','artsakh',12);
INSERT INTO "team_aliases" VALUES('FC Avan Academy','footystats','CL','fc avan academy',13);
INSERT INTO "team_aliases" VALUES('Pyunik','footystats','CL','pyunik',14);
INSERT INTO "team_aliases" VALUES('Banants','footystats','CL','banants',15);
INSERT INTO "team_aliases" VALUES('LASK Linz','footystats','CL','lask linz',16);
INSERT INTO "team_aliases" VALUES('Rapid Wien','footystats','CL','rapid wien',17);
INSERT INTO "team_aliases" VALUES('Salzburg','footystats','CL','salzburg',18);
INSERT INTO "team_aliases" VALUES('Sturm Graz','footystats','CL','sturm graz',19);
INSERT INTO "team_aliases" VALUES('Neftçi','footystats','CL','neftci',20);
INSERT INTO "team_aliases" VALUES('Qarabağ','footystats','CL','qarabag',21);
INSERT INTO "team_aliases" VALUES('BATE','footystats','CL','bate',22);
INSERT INTO "team_aliases" VALUES('Dinamo Brest','footystats','CL','dinamo brest',23);
INSERT INTO "team_aliases" VALUES('Dinamo Minsk','footystats','CL','dinamo minsk',24);
INSERT INTO "team_aliases" VALUES('Shakhtyor','footystats','CL','shakhtyor',25);
INSERT INTO "team_aliases" VALUES('Anderlecht','football_data','B1','anderlecht',26);
INSERT INTO "team_aliases" VALUES('RSC Anderlecht','footystats','CL','rsc anderlecht',26);
INSERT INTO "team_aliases" VALUES('Antwerp','football_data','B1','antwerp',27);
INSERT INTO "team_aliases" VALUES('Royal Antwerp FC','footystats','CL','royal antwerp fc',27);
INSERT INTO "team_aliases" VALUES('Beerschot VA','football_data','B1','beerschot va',28);
INSERT INTO "team_aliases" VALUES('Cercle Brugge','football_data','B1','cercle brugge',29);
INSERT INTO "team_aliases" VALUES('Charleroi','football_data','B1','charleroi',30);
INSERT INTO "team_aliases" VALUES('Club Brugge','football_data','B1','club brugge',31);
INSERT INTO "team_aliases" VALUES('Club Brugge','footystats','CL','club brugge',31);
INSERT INTO "team_aliases" VALUES('Dender','football_data','B1','dender',32);
INSERT INTO "team_aliases" VALUES('Eupen','football_data','B1','eupen',33);
INSERT INTO "team_aliases" VALUES('Genk','football_data','B1','genk',34);
INSERT INTO "team_aliases" VALUES('KRC Genk','footystats','CL','krc genk',34);
INSERT INTO "team_aliases" VALUES('Gent','football_data','B1','gent',35);
INSERT INTO "team_aliases" VALUES('KAA Gent','footystats','CL','kaa gent',35);
INSERT INTO "team_aliases" VALUES('Kortrijk','football_data','B1','kortrijk',36);
INSERT INTO "team_aliases" VALUES('Lokeren','football_data','B1','lokeren',37);
INSERT INTO "team_aliases" VALUES('Mechelen','football_data','B1','mechelen',38);
INSERT INTO "team_aliases" VALUES('Mouscron','football_data','B1','mouscron',39);
INSERT INTO "team_aliases" VALUES('Mouscron-Peruwelz','football_data','B1','mouscron peruwelz',39);
INSERT INTO "team_aliases" VALUES('Oostende','football_data','B1','oostende',40);
INSERT INTO "team_aliases" VALUES('Oud-Heverlee Leuven','football_data','B1','oud heverlee leuven',41);
INSERT INTO "team_aliases" VALUES('RAAL La Louviere','football_data','B1','raal la louviere',42);
INSERT INTO "team_aliases" VALUES('RWD Molenbeek','football_data','B1','rwd molenbeek',43);
INSERT INTO "team_aliases" VALUES('Seraing','football_data','B1','seraing',44);
INSERT INTO "team_aliases" VALUES('St Truiden','football_data','B1','st truiden',45);
INSERT INTO "team_aliases" VALUES('Standard','football_data','B1','standard',46);
INSERT INTO "team_aliases" VALUES('Standard Liège','footystats','CL','standard liege',46);
INSERT INTO "team_aliases" VALUES('St. Gilloise','football_data','B1','st gilloise',47);
INSERT INTO "team_aliases" VALUES('Union Saint-Gilloise','footystats','CL','union saint gilloise',47);
INSERT INTO "team_aliases" VALUES('Waasland-Beveren','football_data','B1','waasland beveren',48);
INSERT INTO "team_aliases" VALUES('Westerlo','football_data','B1','westerlo',49);
INSERT INTO "team_aliases" VALUES('Waregem','football_data','B1','waregem',50);
INSERT INTO "team_aliases" VALUES('Borac Banja Luka','footystats','CL','borac banja luka',51);
INSERT INTO "team_aliases" VALUES('Sarajevo','footystats','CL','sarajevo',52);
INSERT INTO "team_aliases" VALUES('Zrinjski','footystats','CL','zrinjski',53);
INSERT INTO "team_aliases" VALUES('Ludogorets','footystats','CL','ludogorets',54);
INSERT INTO "team_aliases" VALUES('Dinamo Zagreb','footystats','CL','dinamo zagreb',55);
INSERT INTO "team_aliases" VALUES('Lokomotiva Zagreb','footystats','CL','lokomotiva zagreb',56);
INSERT INTO "team_aliases" VALUES('Rijeka','footystats','CL','rijeka',57);
INSERT INTO "team_aliases" VALUES('AEK Larnaca','footystats','CL','aek larnaca',58);
INSERT INTO "team_aliases" VALUES('APOEL','footystats','CL','apoel',59);
INSERT INTO "team_aliases" VALUES('Apollon','footystats','CL','apollon',60);
INSERT INTO "team_aliases" VALUES('Aris','footystats','CL','aris',61);
INSERT INTO "team_aliases" VALUES('Omonia Nicosia','footystats','CL','omonia nicosia',62);
INSERT INTO "team_aliases" VALUES('Paphos','footystats','CL','paphos',63);
INSERT INTO "team_aliases" VALUES('Slavia Praha','footystats','CL','slavia praha',64);
INSERT INTO "team_aliases" VALUES('Sparta Praha','footystats','CL','sparta praha',65);
INSERT INTO "team_aliases" VALUES('Viktoria Plzeň','footystats','CL','viktoria plzen',66);
INSERT INTO "team_aliases" VALUES('Brøndby','footystats','CL','brondby',67);
INSERT INTO "team_aliases" VALUES('København','footystats','CL','kobenhavn',68);
INSERT INTO "team_aliases" VALUES('Midtjylland','footystats','CL','midtjylland',69);
INSERT INTO "team_aliases" VALUES('Arsenal','football_data','E0','arsenal',70);
INSERT INTO "team_aliases" VALUES('Arsenal','footystats','CL','arsenal',70);
INSERT INTO "team_aliases" VALUES('Aston Villa','football_data','E0','aston villa',71);
INSERT INTO "team_aliases" VALUES('Aston Villa','footystats','CL','aston villa',71);
INSERT INTO "team_aliases" VALUES('Bournemouth','football_data','E0','bournemouth',72);
INSERT INTO "team_aliases" VALUES('Brentford','football_data','E0','brentford',73);
INSERT INTO "team_aliases" VALUES('Brighton','football_data','E0','brighton',74);
INSERT INTO "team_aliases" VALUES('Burnley','football_data','E0','burnley',75);
INSERT INTO "team_aliases" VALUES('Chelsea','football_data','E0','chelsea',76);
INSERT INTO "team_aliases" VALUES('Chelsea','footystats','CL','chelsea',76);
INSERT INTO "team_aliases" VALUES('Crystal Palace','football_data','E0','crystal palace',77);
INSERT INTO "team_aliases" VALUES('Everton','football_data','E0','everton',78);
INSERT INTO "team_aliases" VALUES('Fulham','football_data','E0','fulham',79);
INSERT INTO "team_aliases" VALUES('Huddersfield','football_data','E0','huddersfield',80);
INSERT INTO "team_aliases" VALUES('Hull','football_data','E0','hull',81);
INSERT INTO "team_aliases" VALUES('Ipswich','football_data','E0','ipswich',82);
INSERT INTO "team_aliases" VALUES('Leeds','football_data','E0','leeds',83);
INSERT INTO "team_aliases" VALUES('Leicester','football_data','E0','leicester',84);
INSERT INTO "team_aliases" VALUES('Leicester City','footystats','CL','leicester city',84);
INSERT INTO "team_aliases" VALUES('Liverpool','football_data','E0','liverpool',85);
INSERT INTO "team_aliases" VALUES('Liverpool','footystats','CL','liverpool',85);
INSERT INTO "team_aliases" VALUES('Luton','football_data','E0','luton',86);
INSERT INTO "team_aliases" VALUES('Man City','football_data','E0','man city',87);
INSERT INTO "team_aliases" VALUES('Manchester City','footystats','CL','manchester city',87);
INSERT INTO "team_aliases" VALUES('Man United','football_data','E0','man united',88);
INSERT INTO "team_aliases" VALUES('Manchester United','footystats','CL','manchester united',88);
INSERT INTO "team_aliases" VALUES('Middlesbrough','football_data','E0','middlesbrough',89);
INSERT INTO "team_aliases" VALUES('Newcastle','football_data','E0','newcastle',90);
INSERT INTO "team_aliases" VALUES('Newcastle United','footystats','CL','newcastle united',90);
INSERT INTO "team_aliases" VALUES('Norwich','football_data','E0','norwich',91);
INSERT INTO "team_aliases" VALUES('Nott''m Forest','football_data','E0','nott m forest',92);
INSERT INTO "team_aliases" VALUES('Sheffield United','football_data','E0','sheffield united',93);
INSERT INTO "team_aliases" VALUES('Southampton','football_data','E0','southampton',94);
INSERT INTO "team_aliases" VALUES('Stoke','football_data','E0','stoke',95);
INSERT INTO "team_aliases" VALUES('Sunderland','football_data','E0','sunderland',96);
INSERT INTO "team_aliases" VALUES('Tottenham','football_data','E0','tottenham',97);
INSERT INTO "team_aliases" VALUES('Tottenham Hotspur','footystats','CL','tottenham hotspur',97);
INSERT INTO "team_aliases" VALUES('Watford','football_data','E0','watford',98);
INSERT INTO "team_aliases" VALUES('West Brom','football_data','E0','west brom',99);
INSERT INTO "team_aliases" VALUES('West Ham','football_data','E0','west ham',100);
INSERT INTO "team_aliases" VALUES('Wolves','football_data','E0','wolves',101);
INSERT INTO "team_aliases" VALUES('FCI Tallinn','footystats','CL','fci tallinn',102);
INSERT INTO "team_aliases" VALUES('Tallinna FC Flora','footystats','CL','tallinna fc flora',103);
INSERT INTO "team_aliases" VALUES('Tallinna FC Levadia','footystats','CL','tallinna fc levadia',104);
INSERT INTO "team_aliases" VALUES('Nõmme Kalju','footystats','CL','nomme kalju',105);
INSERT INTO "team_aliases" VALUES('B36','footystats','CL','b36',106);
INSERT INTO "team_aliases" VALUES('HB','footystats','CL','hb',107);
INSERT INTO "team_aliases" VALUES('KÍ','footystats','CL','ki',108);
INSERT INTO "team_aliases" VALUES('Víkingur','footystats','CL','vikingur',109);
INSERT INTO "team_aliases" VALUES('HJK','footystats','CL','hjk',110);
INSERT INTO "team_aliases" VALUES('Mariehamn','footystats','CL','mariehamn',111);
INSERT INTO "team_aliases" VALUES('KuPS','footystats','CL','kups',112);
INSERT INTO "team_aliases" VALUES('SJK','footystats','CL','sjk',113);
INSERT INTO "team_aliases" VALUES('Ajaccio','football_data','F1','ajaccio',114);
INSERT INTO "team_aliases" VALUES('Amiens','football_data','F1','amiens',115);
INSERT INTO "team_aliases" VALUES('Angers','football_data','F1','angers',116);
INSERT INTO "team_aliases" VALUES('Auxerre','football_data','F1','auxerre',117);
INSERT INTO "team_aliases" VALUES('Bastia','football_data','F1','bastia',118);
INSERT INTO "team_aliases" VALUES('Bordeaux','football_data','F1','bordeaux',119);
INSERT INTO "team_aliases" VALUES('Brest','football_data','F1','brest',120);
INSERT INTO "team_aliases" VALUES('Brest','footystats','CL','brest',120);
INSERT INTO "team_aliases" VALUES('Caen','football_data','F1','caen',121);
INSERT INTO "team_aliases" VALUES('Clermont','football_data','F1','clermont',122);
INSERT INTO "team_aliases" VALUES('Dijon','football_data','F1','dijon',123);
INSERT INTO "team_aliases" VALUES('Ajaccio GFCO','football_data','F1','ajaccio gfco',124);
INSERT INTO "team_aliases" VALUES('Guingamp','football_data','F1','guingamp',125);
INSERT INTO "team_aliases" VALUES('Le Havre','football_data','F1','le havre',126);
INSERT INTO "team_aliases" VALUES('Lens','football_data','F1','lens',127);
INSERT INTO "team_aliases" VALUES('Lens','footystats','CL','lens',127);
INSERT INTO "team_aliases" VALUES('Lille','football_data','F1','lille',128);
INSERT INTO "team_aliases" VALUES('Lille','footystats','CL','lille',128);
INSERT INTO "team_aliases" VALUES('Lorient','football_data','F1','lorient',129);
INSERT INTO "team_aliases" VALUES('Lyon','football_data','F1','lyon',130);
INSERT INTO "team_aliases" VALUES('Olympique Lyonnais','footystats','CL','olympique lyonnais',130);
INSERT INTO "team_aliases" VALUES('Marseille','football_data','F1','marseille',131);
INSERT INTO "team_aliases" VALUES('Olympique Marseille','footystats','CL','olympique marseille',131);
INSERT INTO "team_aliases" VALUES('Metz','football_data','F1','metz',132);
INSERT INTO "team_aliases" VALUES('Monaco','football_data','F1','monaco',133);
INSERT INTO "team_aliases" VALUES('Monaco','footystats','CL','monaco',133);
INSERT INTO "team_aliases" VALUES('Montpellier','football_data','F1','montpellier',134);
INSERT INTO "team_aliases" VALUES('Nancy','football_data','F1','nancy',135);
INSERT INTO "team_aliases" VALUES('Nantes','football_data','F1','nantes',136);
INSERT INTO "team_aliases" VALUES('Nice','football_data','F1','nice',137);
INSERT INTO "team_aliases" VALUES('Nice','footystats','CL','nice',137);
INSERT INTO "team_aliases" VALUES('Nimes','football_data','F1','nimes',138);
INSERT INTO "team_aliases" VALUES('Paris FC','football_data','F1','paris fc',139);
INSERT INTO "team_aliases" VALUES('Paris SG','football_data','F1','paris sg',140);
INSERT INTO "team_aliases" VALUES('PSG','footystats','CL','psg',140);
INSERT INTO "team_aliases" VALUES('Reims','football_data','F1','reims',141);
INSERT INTO "team_aliases" VALUES('Rennes','football_data','F1','rennes',142);
INSERT INTO "team_aliases" VALUES('Rennes','footystats','CL','rennes',142);
INSERT INTO "team_aliases" VALUES('St Etienne','football_data','F1','st etienne',143);
INSERT INTO "team_aliases" VALUES('Strasbourg','football_data','F1','strasbourg',144);
INSERT INTO "team_aliases" VALUES('Toulouse','football_data','F1','toulouse',145);
INSERT INTO "team_aliases" VALUES('Troyes','football_data','F1','troyes',146);
INSERT INTO "team_aliases" VALUES('Dila','footystats','CL','dila',147);
INSERT INTO "team_aliases" VALUES('Dinamo Batumi','footystats','CL','dinamo batumi',148);
INSERT INTO "team_aliases" VALUES('Dinamo Tbilisi','footystats','CL','dinamo tbilisi',149);
INSERT INTO "team_aliases" VALUES('Saburtalo','footystats','CL','saburtalo',150);
INSERT INTO "team_aliases" VALUES('Samtredia','footystats','CL','samtredia',151);
INSERT INTO "team_aliases" VALUES('Torpedo Kutaisi','footystats','CL','torpedo kutaisi',152);
INSERT INTO "team_aliases" VALUES('Bielefeld','football_data','D1','bielefeld',153);
INSERT INTO "team_aliases" VALUES('Augsburg','football_data','D1','augsburg',154);
INSERT INTO "team_aliases" VALUES('Leverkusen','football_data','D1','leverkusen',155);
INSERT INTO "team_aliases" VALUES('Bayer Leverkusen','footystats','CL','bayer leverkusen',155);
INSERT INTO "team_aliases" VALUES('Bayern Munich','football_data','D1','bayern munich',156);
INSERT INTO "team_aliases" VALUES('Bayern München','footystats','CL','bayern munchen',156);
INSERT INTO "team_aliases" VALUES('Bochum','football_data','D1','bochum',157);
INSERT INTO "team_aliases" VALUES('Dortmund','football_data','D1','dortmund',158);
INSERT INTO "team_aliases" VALUES('Borussia Dortmund','footystats','CL','borussia dortmund',158);
INSERT INTO "team_aliases" VALUES('M''gladbach','football_data','D1','m gladbach',159);
INSERT INTO "team_aliases" VALUES('Borussia M''gladbach','footystats','CL','borussia m gladbach',159);
INSERT INTO "team_aliases" VALUES('Darmstadt','football_data','D1','darmstadt',160);
INSERT INTO "team_aliases" VALUES('Ein Frankfurt','football_data','D1','ein frankfurt',161);
INSERT INTO "team_aliases" VALUES('Eintracht Frankfurt','footystats','CL','eintracht frankfurt',161);
INSERT INTO "team_aliases" VALUES('FC Koln','football_data','D1','fc koln',162);
INSERT INTO "team_aliases" VALUES('Fortuna Dusseldorf','football_data','D1','fortuna dusseldorf',163);
INSERT INTO "team_aliases" VALUES('Freiburg','football_data','D1','freiburg',164);
INSERT INTO "team_aliases" VALUES('Greuther Furth','football_data','D1','greuther furth',165);
INSERT INTO "team_aliases" VALUES('Hamburg','football_data','D1','hamburg',166);
INSERT INTO "team_aliases" VALUES('Hannover','football_data','D1','hannover',167);
INSERT INTO "team_aliases" VALUES('Heidenheim','football_data','D1','heidenheim',168);
INSERT INTO "team_aliases" VALUES('Hertha','football_data','D1','hertha',169);
INSERT INTO "team_aliases" VALUES('Hoffenheim','football_data','D1','hoffenheim',170);
INSERT INTO "team_aliases" VALUES('Hoffenheim','footystats','CL','hoffenheim',170);
INSERT INTO "team_aliases" VALUES('Holstein Kiel','football_data','D1','holstein kiel',171);
INSERT INTO "team_aliases" VALUES('Ingolstadt','football_data','D1','ingolstadt',172);
INSERT INTO "team_aliases" VALUES('Mainz','football_data','D1','mainz',173);
INSERT INTO "team_aliases" VALUES('Nurnberg','football_data','D1','nurnberg',174);
INSERT INTO "team_aliases" VALUES('Paderborn','football_data','D1','paderborn',175);
INSERT INTO "team_aliases" VALUES('RB Leipzig','football_data','D1','rb leipzig',176);
INSERT INTO "team_aliases" VALUES('RB Leipzig','footystats','CL','rb leipzig',176);
INSERT INTO "team_aliases" VALUES('Schalke 04','football_data','D1','schalke 04',177);
INSERT INTO "team_aliases" VALUES('Schalke 04','footystats','CL','schalke 04',177);
INSERT INTO "team_aliases" VALUES('St Pauli','football_data','D1','st pauli',178);
INSERT INTO "team_aliases" VALUES('Union Berlin','football_data','D1','union berlin',179);
INSERT INTO "team_aliases" VALUES('Union Berlin','footystats','CL','union berlin',179);
INSERT INTO "team_aliases" VALUES('Stuttgart','football_data','D1','stuttgart',180);
INSERT INTO "team_aliases" VALUES('Stuttgart','footystats','CL','stuttgart',180);
INSERT INTO "team_aliases" VALUES('Werder Bremen','football_data','D1','werder bremen',181);
INSERT INTO "team_aliases" VALUES('Wolfsburg','football_data','D1','wolfsburg',182);
INSERT INTO "team_aliases" VALUES('Wolfsburg','footystats','CL','wolfsburg',182);
INSERT INTO "team_aliases" VALUES('Europa','footystats','CL','europa',183);
INSERT INTO "team_aliases" VALUES('Lincoln Red Imps','footystats','CL','lincoln red imps',184);
INSERT INTO "team_aliases" VALUES('AEK','football_data','G1','aek',185);
INSERT INTO "team_aliases" VALUES('AEK Athens','footystats','CL','aek athens',185);
INSERT INTO "team_aliases" VALUES('Apollon','football_data','G1','apollon',186);
INSERT INTO "team_aliases" VALUES('Aris','football_data','G1','aris',187);
INSERT INTO "team_aliases" VALUES('Asteras Tripolis','football_data','G1','asteras tripolis',188);
INSERT INTO "team_aliases" VALUES('Atromitos','football_data','G1','atromitos',189);
INSERT INTO "team_aliases" VALUES('Ionikos','football_data','G1','ionikos',190);
INSERT INTO "team_aliases" VALUES('Iraklis','football_data','G1','iraklis',191);
INSERT INTO "team_aliases" VALUES('Athens Kallithea','football_data','G1','athens kallithea',192);
INSERT INTO "team_aliases" VALUES('Kallonis','football_data','G1','kallonis',193);
INSERT INTO "team_aliases" VALUES('Kerkyra','football_data','G1','kerkyra',194);
INSERT INTO "team_aliases" VALUES('Kifisia','football_data','G1','kifisia',195);
INSERT INTO "team_aliases" VALUES('Lamia','football_data','G1','lamia',196);
INSERT INTO "team_aliases" VALUES('Larisa','football_data','G1','larisa',197);
INSERT INTO "team_aliases" VALUES('Levadeiakos','football_data','G1','levadeiakos',198);
INSERT INTO "team_aliases" VALUES('OFI Crete','football_data','G1','ofi crete',199);
INSERT INTO "team_aliases" VALUES('Olympiakos','football_data','G1','olympiakos',200);
INSERT INTO "team_aliases" VALUES('Olympiakos Piraeus','footystats','CL','olympiakos piraeus',200);
INSERT INTO "team_aliases" VALUES('PAOK','football_data','G1','paok',201);
INSERT INTO "team_aliases" VALUES('PAOK','footystats','CL','paok',201);
INSERT INTO "team_aliases" VALUES('Giannina','football_data','G1','giannina',202);
INSERT INTO "team_aliases" VALUES('Panathinaikos','football_data','G1','panathinaikos',203);
INSERT INTO "team_aliases" VALUES('Panathinaikos','footystats','CL','panathinaikos',203);
INSERT INTO "team_aliases" VALUES('Panetolikos','football_data','G1','panetolikos',204);
INSERT INTO "team_aliases" VALUES('Panionios','football_data','G1','panionios',205);
INSERT INTO "team_aliases" VALUES('Panserraikos','football_data','G1','panserraikos',206);
INSERT INTO "team_aliases" VALUES('Panthrakikos','football_data','G1','panthrakikos',207);
INSERT INTO "team_aliases" VALUES('Platanias','football_data','G1','platanias',208);
INSERT INTO "team_aliases" VALUES('Veria','football_data','G1','veria',209);
INSERT INTO "team_aliases" VALUES('Volos NFC','football_data','G1','volos nfc',210);
INSERT INTO "team_aliases" VALUES('Xanthi','football_data','G1','xanthi',211);
INSERT INTO "team_aliases" VALUES('Honvéd','footystats','CL','honved',212);
INSERT INTO "team_aliases" VALUES('Videoton','footystats','CL','videoton',213);
INSERT INTO "team_aliases" VALUES('Ferencváros','footystats','CL','ferencvaros',214);
INSERT INTO "team_aliases" VALUES('Breidablik','footystats','CL','breidablik',215);
INSERT INTO "team_aliases" VALUES('FH','footystats','CL','fh',216);
INSERT INTO "team_aliases" VALUES('KR','footystats','CL','kr',217);
INSERT INTO "team_aliases" VALUES('Stjarnan','footystats','CL','stjarnan',218);
INSERT INTO "team_aliases" VALUES('Valur','footystats','CL','valur',219);
INSERT INTO "team_aliases" VALUES('Víkingur Reykjavík','footystats','CL','vikingur reykjavik',220);
INSERT INTO "team_aliases" VALUES('Hapoel Be''er Sheva','footystats','CL','hapoel be er sheva',221);
INSERT INTO "team_aliases" VALUES('Maccabi Haifa','footystats','CL','maccabi haifa',222);
INSERT INTO "team_aliases" VALUES('Maccabi Tel Aviv','footystats','CL','maccabi tel aviv',223);
INSERT INTO "team_aliases" VALUES('Milan','football_data','I1','milan',224);
INSERT INTO "team_aliases" VALUES('AC Milan','footystats','CL','ac milan',224);
INSERT INTO "team_aliases" VALUES('Atalanta','football_data','I1','atalanta',225);
INSERT INTO "team_aliases" VALUES('Atalanta','footystats','CL','atalanta',225);
INSERT INTO "team_aliases" VALUES('Benevento','football_data','I1','benevento',226);
INSERT INTO "team_aliases" VALUES('Bologna','football_data','I1','bologna',227);
INSERT INTO "team_aliases" VALUES('Bologna','footystats','CL','bologna',227);
INSERT INTO "team_aliases" VALUES('Brescia','football_data','I1','brescia',228);
INSERT INTO "team_aliases" VALUES('Cagliari','football_data','I1','cagliari',229);
INSERT INTO "team_aliases" VALUES('Carpi','football_data','I1','carpi',230);
INSERT INTO "team_aliases" VALUES('Chievo','football_data','I1','chievo',231);
INSERT INTO "team_aliases" VALUES('Como','football_data','I1','como',232);
INSERT INTO "team_aliases" VALUES('Cremonese','football_data','I1','cremonese',233);
INSERT INTO "team_aliases" VALUES('Crotone','football_data','I1','crotone',234);
INSERT INTO "team_aliases" VALUES('Empoli','football_data','I1','empoli',235);
INSERT INTO "team_aliases" VALUES('Fiorentina','football_data','I1','fiorentina',236);
INSERT INTO "team_aliases" VALUES('Frosinone','football_data','I1','frosinone',237);
INSERT INTO "team_aliases" VALUES('Genoa','football_data','I1','genoa',238);
INSERT INTO "team_aliases" VALUES('Verona','football_data','I1','verona',239);
INSERT INTO "team_aliases" VALUES('Inter','football_data','I1','inter',240);
INSERT INTO "team_aliases" VALUES('Inter Milan','footystats','CL','inter milan',240);
INSERT INTO "team_aliases" VALUES('Juventus','football_data','I1','juventus',241);
INSERT INTO "team_aliases" VALUES('Juventus','footystats','CL','juventus',241);
INSERT INTO "team_aliases" VALUES('Lazio','football_data','I1','lazio',242);
INSERT INTO "team_aliases" VALUES('Lazio','footystats','CL','lazio',242);
INSERT INTO "team_aliases" VALUES('Lecce','football_data','I1','lecce',243);
INSERT INTO "team_aliases" VALUES('Monza','football_data','I1','monza',244);
INSERT INTO "team_aliases" VALUES('Napoli','football_data','I1','napoli',245);
INSERT INTO "team_aliases" VALUES('Napoli','footystats','CL','napoli',245);
INSERT INTO "team_aliases" VALUES('Palermo','football_data','I1','palermo',246);
INSERT INTO "team_aliases" VALUES('Parma','football_data','I1','parma',247);
INSERT INTO "team_aliases" VALUES('Pescara','football_data','I1','pescara',248);
INSERT INTO "team_aliases" VALUES('Pisa','football_data','I1','pisa',249);
INSERT INTO "team_aliases" VALUES('Roma','football_data','I1','roma',250);
INSERT INTO "team_aliases" VALUES('Roma','footystats','CL','roma',250);
INSERT INTO "team_aliases" VALUES('Spal','football_data','I1','spal',251);
INSERT INTO "team_aliases" VALUES('Salernitana','football_data','I1','salernitana',252);
INSERT INTO "team_aliases" VALUES('Sampdoria','football_data','I1','sampdoria',253);
INSERT INTO "team_aliases" VALUES('Sassuolo','football_data','I1','sassuolo',254);
INSERT INTO "team_aliases" VALUES('Spezia','football_data','I1','spezia',255);
INSERT INTO "team_aliases" VALUES('Torino','football_data','I1','torino',256);
INSERT INTO "team_aliases" VALUES('Udinese','football_data','I1','udinese',257);
INSERT INTO "team_aliases" VALUES('Venezia','football_data','I1','venezia',258);
INSERT INTO "team_aliases" VALUES('Astana','footystats','CL','astana',259);
INSERT INTO "team_aliases" VALUES('Kairat','footystats','CL','kairat',260);
INSERT INTO "team_aliases" VALUES('Ordabasy','footystats','CL','ordabasy',261);
INSERT INTO "team_aliases" VALUES('Tobol','footystats','CL','tobol',262);
INSERT INTO "team_aliases" VALUES('Ballkani','footystats','CL','ballkani',263);
INSERT INTO "team_aliases" VALUES('Drita','footystats','CL','drita',264);
INSERT INTO "team_aliases" VALUES('Feronikeli','footystats','CL','feronikeli',265);
INSERT INTO "team_aliases" VALUES('Prishtina','footystats','CL','prishtina',266);
INSERT INTO "team_aliases" VALUES('Trepça''89','footystats','CL','trepca 89',267);
INSERT INTO "team_aliases" VALUES('Liepāja','footystats','CL','liepaja',268);
INSERT INTO "team_aliases" VALUES('Riga','footystats','CL','riga',269);
INSERT INTO "team_aliases" VALUES('Rīgas FS','footystats','CL','rigas fs',270);
INSERT INTO "team_aliases" VALUES('Spartaks Jūrmala','footystats','CL','spartaks jurmala',271);
INSERT INTO "team_aliases" VALUES('Valmiera / BSS','footystats','CL','valmiera bss',272);
INSERT INTO "team_aliases" VALUES('Ventspils','footystats','CL','ventspils',273);
INSERT INTO "team_aliases" VALUES('Panevėžys','footystats','CL','panevezys',274);
INSERT INTO "team_aliases" VALUES('Sūduva','footystats','CL','suduva',275);
INSERT INTO "team_aliases" VALUES('Žalgiris','footystats','CL','zalgiris',276);
INSERT INTO "team_aliases" VALUES('Differdange 03','footystats','CL','differdange 03',277);
INSERT INTO "team_aliases" VALUES('F91 Dudelange','footystats','CL','f91 dudelange',278);
INSERT INTO "team_aliases" VALUES('Fola Esch','footystats','CL','fola esch',279);
INSERT INTO "team_aliases" VALUES('Swift Hesperange','footystats','CL','swift hesperange',280);
INSERT INTO "team_aliases" VALUES('Floriana','footystats','CL','floriana',281);
INSERT INTO "team_aliases" VALUES('Hamrun Spartans','footystats','CL','hamrun spartans',282);
INSERT INTO "team_aliases" VALUES('Hibernians','footystats','CL','hibernians',283);
INSERT INTO "team_aliases" VALUES('Valletta','footystats','CL','valletta',284);
INSERT INTO "team_aliases" VALUES('Milsami','footystats','CL','milsami',285);
INSERT INTO "team_aliases" VALUES('Petrocub','footystats','CL','petrocub',286);
INSERT INTO "team_aliases" VALUES('Sheriff','footystats','CL','sheriff',287);
INSERT INTO "team_aliases" VALUES('Budućnost','footystats','CL','buducnost',288);
INSERT INTO "team_aliases" VALUES('Dečić','footystats','CL','decic',289);
INSERT INTO "team_aliases" VALUES('Mladost','footystats','CL','mladost',290);
INSERT INTO "team_aliases" VALUES('Rudar','footystats','CL','rudar',291);
INSERT INTO "team_aliases" VALUES('Sutjeska','footystats','CL','sutjeska',292);
INSERT INTO "team_aliases" VALUES('Den Haag','football_data','N1','den haag',293);
INSERT INTO "team_aliases" VALUES('AZ Alkmaar','football_data','N1','az alkmaar',294);
INSERT INTO "team_aliases" VALUES('AZ','footystats','CL','az',294);
INSERT INTO "team_aliases" VALUES('Ajax','football_data','N1','ajax',295);
INSERT INTO "team_aliases" VALUES('Ajax','footystats','CL','ajax',295);
INSERT INTO "team_aliases" VALUES('Almere City','football_data','N1','almere city',296);
INSERT INTO "team_aliases" VALUES('Cambuur','football_data','N1','cambuur',297);
INSERT INTO "team_aliases" VALUES('Graafschap','football_data','N1','graafschap',298);
INSERT INTO "team_aliases" VALUES('FC Emmen','football_data','N1','fc emmen',299);
INSERT INTO "team_aliases" VALUES('Excelsior','football_data','N1','excelsior',300);
INSERT INTO "team_aliases" VALUES('Feyenoord','football_data','N1','feyenoord',301);
INSERT INTO "team_aliases" VALUES('Feyenoord','footystats','CL','feyenoord',301);
INSERT INTO "team_aliases" VALUES('For Sittard','football_data','N1','for sittard',302);
INSERT INTO "team_aliases" VALUES('Go Ahead Eagles','football_data','N1','go ahead eagles',303);
INSERT INTO "team_aliases" VALUES('Groningen','football_data','N1','groningen',304);
INSERT INTO "team_aliases" VALUES('Heerenveen','football_data','N1','heerenveen',305);
INSERT INTO "team_aliases" VALUES('Heracles','football_data','N1','heracles',306);
INSERT INTO "team_aliases" VALUES('NAC Breda','football_data','N1','nac breda',307);
INSERT INTO "team_aliases" VALUES('Nijmegen','football_data','N1','nijmegen',308);
INSERT INTO "team_aliases" VALUES('Zwolle','football_data','N1','zwolle',309);
INSERT INTO "team_aliases" VALUES('PSV Eindhoven','football_data','N1','psv eindhoven',310);
INSERT INTO "team_aliases" VALUES('PSV','footystats','CL','psv',310);
INSERT INTO "team_aliases" VALUES('Waalwijk','football_data','N1','waalwijk',311);
INSERT INTO "team_aliases" VALUES('Roda','football_data','N1','roda',312);
INSERT INTO "team_aliases" VALUES('Sparta Rotterdam','football_data','N1','sparta rotterdam',313);
INSERT INTO "team_aliases" VALUES('Telstar','football_data','N1','telstar',314);
INSERT INTO "team_aliases" VALUES('Twente','football_data','N1','twente',315);
INSERT INTO "team_aliases" VALUES('Twente','footystats','CL','twente',315);
INSERT INTO "team_aliases" VALUES('Utrecht','football_data','N1','utrecht',316);
INSERT INTO "team_aliases" VALUES('VVV Venlo','football_data','N1','vvv venlo',317);
INSERT INTO "team_aliases" VALUES('Vitesse','football_data','N1','vitesse',318);
INSERT INTO "team_aliases" VALUES('Volendam','football_data','N1','volendam',319);
INSERT INTO "team_aliases" VALUES('Willem II','football_data','N1','willem ii',320);
INSERT INTO "team_aliases" VALUES('Shkendija','footystats','CL','shkendija',321);
INSERT INTO "team_aliases" VALUES('Shkupi','footystats','CL','shkupi',322);
INSERT INTO "team_aliases" VALUES('Sileks','footystats','CL','sileks',323);
INSERT INTO "team_aliases" VALUES('Struga','footystats','CL','struga',324);
INSERT INTO "team_aliases" VALUES('Vardar','footystats','CL','vardar',325);
INSERT INTO "team_aliases" VALUES('Crusaders','footystats','CL','crusaders',326);
INSERT INTO "team_aliases" VALUES('Larne','footystats','CL','larne',327);
INSERT INTO "team_aliases" VALUES('Linfield','footystats','CL','linfield',328);
INSERT INTO "team_aliases" VALUES('FK Bodo - Glimt','footystats','CL','fk bodo glimt',329);
INSERT INTO "team_aliases" VALUES('Brann','footystats','CL','brann',330);
INSERT INTO "team_aliases" VALUES('Molde','footystats','CL','molde',331);
INSERT INTO "team_aliases" VALUES('Rosenborg','footystats','CL','rosenborg',332);
INSERT INTO "team_aliases" VALUES('Jagiellonia Białystok','footystats','CL','jagiellonia bialystok',333);
INSERT INTO "team_aliases" VALUES('Lech Poznań','footystats','CL','lech poznan',334);
INSERT INTO "team_aliases" VALUES('Legia Warszawa','footystats','CL','legia warszawa',335);
INSERT INTO "team_aliases" VALUES('Piast Gliwice','footystats','CL','piast gliwice',336);
INSERT INTO "team_aliases" VALUES('Raków Częstochowa','footystats','CL','rakow czestochowa',337);
INSERT INTO "team_aliases" VALUES('AVS','football_data','P1','avs',338);
INSERT INTO "team_aliases" VALUES('Academica','football_data','P1','academica',339);
INSERT INTO "team_aliases" VALUES('Alverca','football_data','P1','alverca',340);
INSERT INTO "team_aliases" VALUES('Arouca','football_data','P1','arouca',341);
INSERT INTO "team_aliases" VALUES('Belenenses','football_data','P1','belenenses',342);
INSERT INTO "team_aliases" VALUES('Benfica','football_data','P1','benfica',343);
INSERT INTO "team_aliases" VALUES('Benfica','footystats','CL','benfica',343);
INSERT INTO "team_aliases" VALUES('Boavista','football_data','P1','boavista',344);
INSERT INTO "team_aliases" VALUES('Casa Pia','football_data','P1','casa pia',345);
INSERT INTO "team_aliases" VALUES('Chaves','football_data','P1','chaves',346);
INSERT INTO "team_aliases" VALUES('Aves','football_data','P1','aves',347);
INSERT INTO "team_aliases" VALUES('Estoril','football_data','P1','estoril',348);
INSERT INTO "team_aliases" VALUES('Estrela','football_data','P1','estrela',349);
INSERT INTO "team_aliases" VALUES('Famalicao','football_data','P1','famalicao',350);
INSERT INTO "team_aliases" VALUES('Farense','football_data','P1','farense',351);
INSERT INTO "team_aliases" VALUES('Feirense','football_data','P1','feirense',352);
INSERT INTO "team_aliases" VALUES('Gil Vicente','football_data','P1','gil vicente',353);
INSERT INTO "team_aliases" VALUES('Maritimo','football_data','P1','maritimo',354);
INSERT INTO "team_aliases" VALUES('Moreirense','football_data','P1','moreirense',355);
INSERT INTO "team_aliases" VALUES('Nacional','football_data','P1','nacional',356);
INSERT INTO "team_aliases" VALUES('Pacos Ferreira','football_data','P1','pacos ferreira',357);
INSERT INTO "team_aliases" VALUES('Portimonense','football_data','P1','portimonense',358);
INSERT INTO "team_aliases" VALUES('Porto','football_data','P1','porto',359);
INSERT INTO "team_aliases" VALUES('Porto','footystats','CL','porto',359);
INSERT INTO "team_aliases" VALUES('Rio Ave','football_data','P1','rio ave',360);
INSERT INTO "team_aliases" VALUES('Santa Clara','football_data','P1','santa clara',361);
INSERT INTO "team_aliases" VALUES('Sp Braga','football_data','P1','sp braga',362);
INSERT INTO "team_aliases" VALUES('Sporting Braga','footystats','CL','sporting braga',362);
INSERT INTO "team_aliases" VALUES('Sp Lisbon','football_data','P1','sp lisbon',363);
INSERT INTO "team_aliases" VALUES('Sporting CP','footystats','CL','sporting cp',363);
INSERT INTO "team_aliases" VALUES('Tondela','football_data','P1','tondela',364);
INSERT INTO "team_aliases" VALUES('Uniao Madeira','football_data','P1','uniao madeira',365);
INSERT INTO "team_aliases" VALUES('Guimaraes','football_data','P1','guimaraes',366);
INSERT INTO "team_aliases" VALUES('Setubal','football_data','P1','setubal',367);
INSERT INTO "team_aliases" VALUES('Vizela','football_data','P1','vizela',368);
INSERT INTO "team_aliases" VALUES('Cork City','footystats','CL','cork city',369);
INSERT INTO "team_aliases" VALUES('Dundalk','footystats','CL','dundalk',370);
INSERT INTO "team_aliases" VALUES('Shamrock Rovers','footystats','CL','shamrock rovers',371);
INSERT INTO "team_aliases" VALUES('Shelbourne','footystats','CL','shelbourne',372);
INSERT INTO "team_aliases" VALUES('Astra','footystats','CL','astra',373);
INSERT INTO "team_aliases" VALUES('CFR Cluj','footystats','CL','cfr cluj',374);
INSERT INTO "team_aliases" VALUES('FCSB','footystats','CL','fcsb',375);
INSERT INTO "team_aliases" VALUES('SSC Farul','footystats','CL','ssc farul',376);
INSERT INTO "team_aliases" VALUES('Viitorul','footystats','CL','viitorul',377);
INSERT INTO "team_aliases" VALUES('CSKA Moskva','footystats','CL','cska moskva',378);
INSERT INTO "team_aliases" VALUES('Krasnodar','footystats','CL','krasnodar',379);
INSERT INTO "team_aliases" VALUES('Lokomotiv Moskva','footystats','CL','lokomotiv moskva',380);
INSERT INTO "team_aliases" VALUES('Rostov','footystats','CL','rostov',381);
INSERT INTO "team_aliases" VALUES('Spartak Moskva','footystats','CL','spartak moskva',382);
INSERT INTO "team_aliases" VALUES('Zenit','footystats','CL','zenit',383);
INSERT INTO "team_aliases" VALUES('S.S. Folgore','footystats','CL','s s folgore',384);
INSERT INTO "team_aliases" VALUES('La Fiorita','footystats','CL','la fiorita',385);
INSERT INTO "team_aliases" VALUES('Tre Fiori','footystats','CL','tre fiori',386);
INSERT INTO "team_aliases" VALUES('Tre Penne','footystats','CL','tre penne',387);
INSERT INTO "team_aliases" VALUES('Virtus','footystats','CL','virtus',388);
INSERT INTO "team_aliases" VALUES('Aberdeen','football_data','SC0','aberdeen',389);
INSERT INTO "team_aliases" VALUES('Celtic','football_data','SC0','celtic',390);
INSERT INTO "team_aliases" VALUES('Celtic','footystats','CL','celtic',390);
INSERT INTO "team_aliases" VALUES('Dundee','football_data','SC0','dundee',391);
INSERT INTO "team_aliases" VALUES('Dundee United','football_data','SC0','dundee united',392);
INSERT INTO "team_aliases" VALUES('Falkirk','football_data','SC0','falkirk',393);
INSERT INTO "team_aliases" VALUES('Hamilton','football_data','SC0','hamilton',394);
INSERT INTO "team_aliases" VALUES('Hearts','football_data','SC0','hearts',395);
INSERT INTO "team_aliases" VALUES('Hibernian','football_data','SC0','hibernian',396);
INSERT INTO "team_aliases" VALUES('Inverness C','football_data','SC0','inverness c',397);
INSERT INTO "team_aliases" VALUES('Kilmarnock','football_data','SC0','kilmarnock',398);
INSERT INTO "team_aliases" VALUES('Livingston','football_data','SC0','livingston',399);
INSERT INTO "team_aliases" VALUES('Motherwell','football_data','SC0','motherwell',400);
INSERT INTO "team_aliases" VALUES('Partick','football_data','SC0','partick',401);
INSERT INTO "team_aliases" VALUES('Rangers','football_data','SC0','rangers',402);
INSERT INTO "team_aliases" VALUES('Rangers','footystats','CL','rangers',402);
INSERT INTO "team_aliases" VALUES('Ross County','football_data','SC0','ross county',403);
INSERT INTO "team_aliases" VALUES('St Johnstone','football_data','SC0','st johnstone',404);
INSERT INTO "team_aliases" VALUES('St Mirren','football_data','SC0','st mirren',405);
INSERT INTO "team_aliases" VALUES('Partizan','footystats','CL','partizan',406);
INSERT INTO "team_aliases" VALUES('Red Star Belgrade','footystats','CL','red star belgrade',407);
INSERT INTO "team_aliases" VALUES('Bačka Topola','footystats','CL','backa topola',408);
INSERT INTO "team_aliases" VALUES('Slovan Bratislava','footystats','CL','slovan bratislava',409);
INSERT INTO "team_aliases" VALUES('Spartak Trnava','footystats','CL','spartak trnava',410);
INSERT INTO "team_aliases" VALUES('Trenčín','footystats','CL','trencin',411);
INSERT INTO "team_aliases" VALUES('Žilina','footystats','CL','zilina',412);
INSERT INTO "team_aliases" VALUES('Celje','footystats','CL','celje',413);
INSERT INTO "team_aliases" VALUES('Maribor','footystats','CL','maribor',414);
INSERT INTO "team_aliases" VALUES('Mura','footystats','CL','mura',415);
INSERT INTO "team_aliases" VALUES('Olimpija','footystats','CL','olimpija',416);
INSERT INTO "team_aliases" VALUES('Alaves','football_data','SP1','alaves',417);
INSERT INTO "team_aliases" VALUES('Almeria','football_data','SP1','almeria',418);
INSERT INTO "team_aliases" VALUES('Ath Bilbao','football_data','SP1','ath bilbao',419);
INSERT INTO "team_aliases" VALUES('Athletic Club Bilbao','footystats','CL','athletic club bilbao',419);
INSERT INTO "team_aliases" VALUES('Ath Madrid','football_data','SP1','ath madrid',420);
INSERT INTO "team_aliases" VALUES('Atlético Madrid','footystats','CL','atletico madrid',420);
INSERT INTO "team_aliases" VALUES('Barcelona','football_data','SP1','barcelona',421);
INSERT INTO "team_aliases" VALUES('FC Barcelona','footystats','CL','fc barcelona',421);
INSERT INTO "team_aliases" VALUES('Cadiz','football_data','SP1','cadiz',422);
INSERT INTO "team_aliases" VALUES('Celta','football_data','SP1','celta',423);
INSERT INTO "team_aliases" VALUES('La Coruna','football_data','SP1','la coruna',424);
INSERT INTO "team_aliases" VALUES('Eibar','football_data','SP1','eibar',425);
INSERT INTO "team_aliases" VALUES('Elche','football_data','SP1','elche',426);
INSERT INTO "team_aliases" VALUES('Espanol','football_data','SP1','espanol',427);
INSERT INTO "team_aliases" VALUES('Getafe','football_data','SP1','getafe',428);
INSERT INTO "team_aliases" VALUES('Girona','football_data','SP1','girona',429);
INSERT INTO "team_aliases" VALUES('Girona FC','footystats','CL','girona fc',429);
INSERT INTO "team_aliases" VALUES('Granada','football_data','SP1','granada',430);
INSERT INTO "team_aliases" VALUES('Huesca','football_data','SP1','huesca',431);
INSERT INTO "team_aliases" VALUES('Las Palmas','football_data','SP1','las palmas',432);
INSERT INTO "team_aliases" VALUES('Leganes','football_data','SP1','leganes',433);
INSERT INTO "team_aliases" VALUES('Levante','football_data','SP1','levante',434);
INSERT INTO "team_aliases" VALUES('Malaga','football_data','SP1','malaga',435);
INSERT INTO "team_aliases" VALUES('Mallorca','football_data','SP1','mallorca',436);
INSERT INTO "team_aliases" VALUES('Osasuna','football_data','SP1','osasuna',437);
INSERT INTO "team_aliases" VALUES('Vallecano','football_data','SP1','vallecano',438);
INSERT INTO "team_aliases" VALUES('Betis','football_data','SP1','betis',439);
INSERT INTO "team_aliases" VALUES('Real Madrid','football_data','SP1','real madrid',440);
INSERT INTO "team_aliases" VALUES('Real Madrid','footystats','CL','real madrid',440);
INSERT INTO "team_aliases" VALUES('Oviedo','football_data','SP1','oviedo',441);
INSERT INTO "team_aliases" VALUES('Sociedad','football_data','SP1','sociedad',442);
INSERT INTO "team_aliases" VALUES('Real Sociedad','footystats','CL','real sociedad',442);
INSERT INTO "team_aliases" VALUES('Valladolid','football_data','SP1','valladolid',443);
INSERT INTO "team_aliases" VALUES('Sevilla','football_data','SP1','sevilla',444);
INSERT INTO "team_aliases" VALUES('Sevilla FC','footystats','CL','sevilla fc',444);
INSERT INTO "team_aliases" VALUES('Sp Gijon','football_data','SP1','sp gijon',445);
INSERT INTO "team_aliases" VALUES('Valencia','football_data','SP1','valencia',446);
INSERT INTO "team_aliases" VALUES('Valencia CF','footystats','CL','valencia cf',446);
INSERT INTO "team_aliases" VALUES('Villarreal','football_data','SP1','villarreal',447);
INSERT INTO "team_aliases" VALUES('Villarreal','footystats','CL','villarreal',447);
INSERT INTO "team_aliases" VALUES('AIK','footystats','CL','aik',448);
INSERT INTO "team_aliases" VALUES('Djurgården','footystats','CL','djurgarden',449);
INSERT INTO "team_aliases" VALUES('Häcken','footystats','CL','hacken',450);
INSERT INTO "team_aliases" VALUES('Malmö FF','footystats','CL','malmo ff',451);
INSERT INTO "team_aliases" VALUES('Norrköping','footystats','CL','norrkoping',452);
INSERT INTO "team_aliases" VALUES('Basel','footystats','CL','basel',453);
INSERT INTO "team_aliases" VALUES('Lugano','footystats','CL','lugano',454);
INSERT INTO "team_aliases" VALUES('Servette','footystats','CL','servette',455);
INSERT INTO "team_aliases" VALUES('Young Boys','footystats','CL','young boys',456);
INSERT INTO "team_aliases" VALUES('Zürich','footystats','CL','zurich',457);
INSERT INTO "team_aliases" VALUES('Ad. Demirspor','football_data','T1','ad demirspor',458);
INSERT INTO "team_aliases" VALUES('Adanaspor','football_data','T1','adanaspor',459);
INSERT INTO "team_aliases" VALUES('Akhisar Belediyespor','football_data','T1','akhisar belediyespor',460);
INSERT INTO "team_aliases" VALUES('Alanyaspor','football_data','T1','alanyaspor',461);
INSERT INTO "team_aliases" VALUES('Altay','football_data','T1','altay',462);
INSERT INTO "team_aliases" VALUES('Ankaragucu','football_data','T1','ankaragucu',463);
INSERT INTO "team_aliases" VALUES('Antalyaspor','football_data','T1','antalyaspor',464);
INSERT INTO "team_aliases" VALUES('Besiktas','football_data','T1','besiktas',465);
INSERT INTO "team_aliases" VALUES('Beşiktaş','footystats','CL','besiktas',465);
INSERT INTO "team_aliases" VALUES('Bodrumspor','football_data','T1','bodrumspor',466);
INSERT INTO "team_aliases" VALUES('Bursaspor','football_data','T1','bursaspor',467);
INSERT INTO "team_aliases" VALUES('Rizespor','football_data','T1','rizespor',468);
INSERT INTO "team_aliases" VALUES('Denizlispor','football_data','T1','denizlispor',469);
INSERT INTO "team_aliases" VALUES('Erzurum BB','football_data','T1','erzurum bb',470);
INSERT INTO "team_aliases" VALUES('Eskisehirspor','football_data','T1','eskisehirspor',471);
INSERT INTO "team_aliases" VALUES('Eyupspor','football_data','T1','eyupspor',472);
INSERT INTO "team_aliases" VALUES('Karagumruk','football_data','T1','karagumruk',473);
INSERT INTO "team_aliases" VALUES('Fenerbahce','football_data','T1','fenerbahce',474);
INSERT INTO "team_aliases" VALUES('Fenerbahçe','footystats','CL','fenerbahce',474);
INSERT INTO "team_aliases" VALUES('Galatasaray','football_data','T1','galatasaray',475);
INSERT INTO "team_aliases" VALUES('Galatasaray','footystats','CL','galatasaray',475);
INSERT INTO "team_aliases" VALUES('Gaziantep','football_data','T1','gaziantep',476);
INSERT INTO "team_aliases" VALUES('Gaziantepspor','football_data','T1','gaziantepspor',477);
INSERT INTO "team_aliases" VALUES('Genclerbirligi','football_data','T1','genclerbirligi',478);
INSERT INTO "team_aliases" VALUES('Giresunspor','football_data','T1','giresunspor',479);
INSERT INTO "team_aliases" VALUES('Goztep','football_data','T1','goztep',480);
INSERT INTO "team_aliases" VALUES('Hatayspor','football_data','T1','hatayspor',481);
INSERT INTO "team_aliases" VALUES('Buyuksehyr','football_data','T1','buyuksehyr',482);
INSERT INTO "team_aliases" VALUES('İstanbul Başakşehir','footystats','CL','istanbul basaksehir',482);
INSERT INTO "team_aliases" VALUES('Istanbulspor','football_data','T1','istanbulspor',483);
INSERT INTO "team_aliases" VALUES('Karabukspor','football_data','T1','karabukspor',484);
INSERT INTO "team_aliases" VALUES('Kasimpasa','football_data','T1','kasimpasa',485);
INSERT INTO "team_aliases" VALUES('Kayserispor','football_data','T1','kayserispor',486);
INSERT INTO "team_aliases" VALUES('Kocaelispor','football_data','T1','kocaelispor',487);
INSERT INTO "team_aliases" VALUES('Konyaspor','football_data','T1','konyaspor',488);
INSERT INTO "team_aliases" VALUES('Mersin Idman Yurdu','football_data','T1','mersin idman yurdu',489);
INSERT INTO "team_aliases" VALUES('Osmanlispor','football_data','T1','osmanlispor',490);
INSERT INTO "team_aliases" VALUES('Pendikspor','football_data','T1','pendikspor',491);
INSERT INTO "team_aliases" VALUES('Samsunspor','football_data','T1','samsunspor',492);
INSERT INTO "team_aliases" VALUES('Sivasspor','football_data','T1','sivasspor',493);
INSERT INTO "team_aliases" VALUES('Trabzonspor','football_data','T1','trabzonspor',494);
INSERT INTO "team_aliases" VALUES('Trabzonspor','footystats','CL','trabzonspor',494);
INSERT INTO "team_aliases" VALUES('Umraniyespor','football_data','T1','umraniyespor',495);
INSERT INTO "team_aliases" VALUES('Yeni Malatyaspor','football_data','T1','yeni malatyaspor',496);
INSERT INTO "team_aliases" VALUES('Dnipro-1','footystats','CL','dnipro 1',497);
INSERT INTO "team_aliases" VALUES('Dynamo Kyiv','footystats','CL','dynamo kyiv',498);
INSERT INTO "team_aliases" VALUES('Shakhtar Donetsk','footystats','CL','shakhtar donetsk',499);
INSERT INTO "team_aliases" VALUES('Cardiff','football_data','E0','cardiff',500);
INSERT INTO "team_aliases" VALUES('Connah''s Quay','footystats','CL','connah s quay',501);
INSERT INTO "team_aliases" VALUES('Swansea','football_data','E0','swansea',502);
INSERT INTO "team_aliases" VALUES('The New Saints','footystats','CL','the new saints',503);

CREATE INDEX idx_alias_team ON team_aliases(team_id);
CREATE INDEX idx_alias_norm ON team_aliases(alias_norm);
CREATE VIEW v_team_alias_map AS
SELECT a.team_id, t.canonical_name, t.country, a.alias, a.source, a.league, t.notes
FROM team_aliases a JOIN teams t USING (team_id);

COMMIT;
